device/urls.py
from django.urls import path, include

from .views import DeviceListView, DeviceDetailView, DeviceCreateView


app_name  = 'device'

urlpatterns = [
    path('', DeviceListView.as_view(), name='device_list'),
    path('device/<int:pk>/', DeviceDetailView.as_view(), name='device_detail'),
    path('device/create/', DeviceCreateView.as_view(), name='device_create'),
]

warning_devices/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework.authtoken.views import obtain_auth_token

from .router import router


urlpatterns = [
	path('api-token-auth/', obtain_auth_token, name='api-token-auth'),
    path('admin/', admin.site.urls),
    path('api/', include(router.urls)),
    path('', include('device.urls')),
]

device/models.py
from django.db import models
from django.shortcuts import reverse



class Device(models.Model):
    TYPE_CHOICES = (
        ('s', 'Сирена'),
        ('m', 'Громкоговоритель'),
    )

    name = models.CharField(max_length=200, verbose_name='Название')
    type = models.CharField(max_length=1, choices=TYPE_CHOICES, verbose_name='Тип устройства', default='siren')
    adress = models.CharField(max_length=200, verbose_name='Адрес')
    latitude = models.DecimalField(max_digits=9999, decimal_places=6, verbose_name='Широта')
    longitude = models.DecimalField(max_digits=9999, decimal_places=6, verbose_name='Долгота')
    radius = models.PositiveIntegerField(verbose_name='Радиус зоны звукопокрытия')

    def get_absolute_url(self):
        return reverse('device:device_detail', kwargs={'pk': self.pk})

    def __str__(self):
    	return self.name

    class Meta:
        verbose_name_plural = 'Устройства'
        verbose_name = 'Устройство'
        ordering = ['-radius']

device/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView, DetailView, CreateView

from .models import Device



class DeviceListView(ListView):
	model = Device
	template_name = 'devices/list.html'
	paginate_by = 10

	def get_context_data(self, **kwargs):
		context = super(DeviceListView, self).get_context_data(**kwargs)
		all_devices = Device.objects.all()
		type = self.request.GET.get('type')
		filter_devices_set = all_devices.filter(type=type)
		context['filter_set'] = filter_devices_set
		return context


class DeviceDetailView(DetailView):
	model = Device
	template_name = 'devices/detail.html'


class DeviceCreateView(CreateView):
	model = Device
	fields = ('name', 'type', 'adress', 'latitude', 'longitude', 'radius')
	template_name = 'devices/create.html'

templates/base.html
<!DOCTYPE html>
<html lang="ru">
<head>
	<meta charset="UTF-8">
	<title>{% block title %}{% endblock title %}</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body>
	<nav class="navbar navbar-expand-lg navbar-light bg-light">
		<div class="collapse navbar-collapse" id="navbarNav">
			<ul class="navbar-nav">
				<li class="nav-item">
					<a class="nav-link" href="{% url 'device:device_list' %}">Список Устройств</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="{% url 'device:device_create' %}">Добавить устройство</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="/admin">Админка</a>
				</li>
			</ul>
		</div>
	</nav>
	<div class="container">
		{% block content %}
		{% endblock content %}
	</div>
</body>
</html>

templates/devices/create.html
{% extends 'base.html' %}}

{% block content %}
	<form action="{% url 'device:device_create'%}" method="POST">
		{% csrf_token %}

		{{ form.as_p }}
		<button type='submit'>добавить</button>
	</form>
{% endblock content %}

templates/devices/detail.html
{% extends 'base.html' %}}

{% block content %}
	<div class="row">
		<div class="col">
			<h1>Усройство {{ object.name }}</h1>
			<h4>Описание</h4>
			<div class="row">
				
				<div class="col-2">
					<p>Тип:</p> 
					<p>Адрес:</p>
					<p>Широта:</p>
					<p>Долгота:</p>
					<p>Радиус действия(м):</p>

				</div>
				<div class="col">
					<p>{{ object.get_type_display }}</p>
					<p>{{ object.adress }}</p>
					<p>{{ object.latitude }}</p>
					<p>{{ object.longitude }}</p>
					<p>{{ object.radius }}</p>
				</div>
			</div>
		</div>
	</div>
{% endblock content %}

templates/devices/list.html
{% extends 'base.html' %}

{% block content %}
	<h1>Устройства</h1>
	<div class="row">
		<div class="col-8">
			<ul class="list-group">
			{% for device in filter_set %}
				<li class="list-group-item mt-1"><a href="{{ device.get_absolute_url }}">{{ device.name }} - {{ device.get_type_display }}</a></li>
			{% empty %}
				{% for device in object_list %}
				    <li class="list-group-item mt-1"><a href="{{ device.get_absolute_url }}">{{ device.name }} - {{ device.get_type_display }}</a></li>
				{% empty %}
				    <li>Еще нет устройств</li>
				{% endfor %}
			{% endfor %}
			</ul>
		</div>


		<div class="col-4">
			<div class="card">
				<div class="card-body">
					<h5 class="card-title">Сортировка</h5>
					<a href="{% url 'device:device_list' %}?type=m" class="card-link">громкоговоритель</a>
					<a href="{% url 'device:device_list' %}?type=s" class="card-link">сирена</a>
				</div>
			</div>
		</div>
	</div>
{% endblock content %}